node{
	stage('build'){
		sh 'python3 -V'
	}
	stage('test'){
		git branch: 'main', url: 'https://github.com/rafaelnisgoski/PUCPR_DevOps.git'
		sh 'python3 hello.py'
	}
	stage('deploy'){
		echo "Tudo feito! :D"
	}
}
