name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:
    
jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: |
                docker buildx build -t ${{ secrets.DOCKER_USER }}/flask-build:latest .
                docker login -u ${{ secrets.DOCKER_USER}} -p ${{ secrets.DOCKER_PASSWORD }}
                docker push ${{ secrets.DOCKER_USER}}/flask-build:latest
                
    sast-test-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: |
                pip install -r requirements.txt
                pip install bandit
                echo "Rodando teste Bandit!"
                bandit -r app.py
                
    deploy-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: |
                echo "Iniciando deploy..."
                docker login -u ${{ secrets.DOCKER_USER}} -p ${{ secrets.DOCKER_PASSWORD }}
                docker pull ${{ secrets.DOCKER_USER }}/flask-build:latest
